### ISSUE TITLE
Queries and mutations not saving when having lots of tabs open

### ISSUE THREAD

**Issue by omgvamp** [prismagraphql/graphql-playground#658]
#### This issue pertains to the following package(s):

- [x] GraphQL Playground - Electron App
- [ ] GraphQL Playground HTML
- [ ] GraphQL Playground
- [ ] GraphQL Playground Express Middleware
- [ ] GraphQL Playground Hapi Middleware
- [ ] GraphQL Playground Koa Middleware
- [ ] GraphQL Playground Lambda Middleware

#### What OS and OS version are you experiencing the issue(s) on?
macOS High Sierra 10.13.4

#### What version of graphql-playground(-electron/-middleware) are you experiencing the issue(s) on?
Version 1.5.6

#### What is the expected behavior?
All queries and mutations are saved upon modifying and restored upon restart.

#### What is the actual behavior?
Queries and mutations are not stored anymore after the error below occurs.

#### What steps may we take to reproduce the behavior?
My queries and mutations aren't saving when I have around 11 tabs (different queries and mutations) open. The console is giving the following error every time I modify anything:

```
app.ad6d65d….js:187687 Uncaught DOMException: Failed to execute 'setItem' on 'Storage': Setting the value of 'graphql-playground' exceeded the quota.
    at lodash_1.debounce.trailing (file:///Applications/GraphQL%20Playground.app/Contents/Resources/app.asar/lib/dist/app.ad6d65daf42880101cd1.js:187687:26)
    at invokeFunc (file:///Applications/GraphQL%20Playground.app/Contents/Resources/app.asar/lib/dist/app.ad6d65daf42880101cd1.js:68386:23)
    at trailingEdge (file:///Applications/GraphQL%20Playground.app/Contents/Resources/app.asar/lib/dist/app.ad6d65daf42880101cd1.js:68433:18)
    at timerExpired (file:///Applications/GraphQL%20Playground.app/Contents/Resources/app.asar/lib/dist/app.ad6d65daf42880101cd1.js:68421:18)
```

Looks like it is out of storage space? Anything I modify after the above error occurs isn't saved.

**Comment by timsuchanek** [comment]
Fixed in the latest version. Please let us know if you still have that issue, then we reopen it!
