### ISSUE TITLE
Linux-AppImage version does not start

### ISSUE THREAD

**Issue by rbi** [prismagraphql/graphql-playground#737]
#### This issue pertains to the following package(s):

- [x] GraphQL Playground - Electron App
- [ ] GraphQL Playground HTML
- [ ] GraphQL Playground
- [ ] GraphQL Playground Express Middleware
- [ ] GraphQL Playground Hapi Middleware
- [ ] GraphQL Playground Koa Middleware
- [ ] GraphQL Playground Lambda Middleware

#### What OS and OS version are you experiencing the issue(s) on?
* Kubuntu 18.04

#### What version of graphql-playground(-electron/-middleware) are you experiencing the issue(s) on?
* 1.6.0

#### What is the expected behavior?
* AppImage version of GraphQL playground starts

#### What is the actual behavior?
* Appimage version of GraphQL fails to start
* The following exception orrcurs
~~~
module.js:545
    throw err;
    ^

Error: Cannot find module '/tmp/.mount_graphqlKjvp1/resources/electron.asar/browser/init.js'
    at Function.Module._resolveFilename (module.js:543:15)
    at Function.Module._load (module.js:473:25)
    at Function.Module.runMain (module.js:683:10)
    at startup (bootstrap_node.js:196:16)
    at bootstrap_node.js:622:3
~~~

#### What steps may we take to reproduce the behavior?
* Start the AppImage
* Click "No" when ask if integration into the System is desired

**Comment by probonopd** [comment]
May be caused by https://github.com/electron-userland/electron-builder/issues/2958

**Comment by codyzu** [comment]
Same problem for me, I'm running Antergos linux. Doesn't matter if I click yes or no when asked about the system integration.

**Comment by codyzu** [comment]
A bit more setup, but the `snap` distribution works on my Linux setup (using the `--dangerous` flag).

**Comment by probonopd** [comment]
Updating electron-builder and then rebuilding the AppImage may solve this.
